require("battisti.options")
require("battisti.remap")
require("battisti.plugins")
require("battisti.functions")
require("battisti.snippets")
require("battisti.autocommands")
require("battisti.filetypes")
